name: CI

on:
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: npm
      - run: npm ci
      - run: npm test
